<?php

/**
 * @file
 *   Implmenting our hooks
 */


/**
 * Implements hook_theme
 */
function module_hero_theme($existing, $type, $theme, $path) {
    return array(
        'hero_list' => array(
            'variables' => array(
                'items' => array(),
                'title' => ''
            ),
        ),
    );
}

/**
 * Implements hook_form_alter
 */
function module_hero_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    if ($form_id == 'node_article_form') {
        $form['field_tags']['#access'] = false;
    }
}